### ISSUE TITLE
Dataset incompletion

### ISSUE THREAD

**Issue by YJ-He** [geodrak/OMBRIA#1]
Thanks for your kindly sharing, this is an impressive dataset for flood mapping with multimodal data. The only question is that the number of paired images and masks is not in line with your published paper. Specifically, there are 844 tiles in your paper, but I only got 624 (train) and 70 (test) tiles. Is there something I missed here? Looking forward to your reply, thanks.

**Comment by geodrak** [comment]
Greetings, apologies for the late response. The missing 150 tiles have been added. These are flood events that took place in 2021 as described in the published paper.

Regards

**Comment by YJ-He** [comment]
@geodrak Thanks for your reply, Got them.
