### ISSUE TITLE
Question about training codes

### ISSUE THREAD

**Issue by DaisyWatermelon** [geodrak/OMBRIA#3]
Hi Georgios,
Thank you so much for sharing your datasets. I read your paper and had a look at your dataset, I am interested to have a try the training and test datasets, but I don't know the what codes you used for training. If you don't mind, can you share your training codes please? Thanks.

**Comment by geodrak** [comment]
Greetings,
I am sorry for the (quite) delayed response. I uploaded the code i used for the project. I worked on Google Colab. I also would like to inform you that due to my technical backround the code is not clean and optimised.

Regards
